<?= $this->extend('templates/admin/layouts/main'); ?>
<?= $this->section('content_header'); ?>
<div class="admin-page-title d-flex flex-column flex-lg-row align-items-lg-end justify-content-between gap-3"><div><span>Konten Website</span><h1>FAQ</h1><p>Kelola pertanyaan umum calon jamaah dan informasi penting sebelum perjalanan.</p></div><div class="d-flex gap-2 flex-wrap"><a href="<?= base_url('/admin/faqs/trash'); ?>" class="btn btn-admin-outline"><i class="bi bi-trash3"></i> Sampah</a><a href="<?= base_url('/admin/faqs/create'); ?>" class="btn btn-admin-primary"><i class="bi bi-plus-lg"></i> Tambah FAQ</a></div></div>
<?= $this->endSection(); ?>
<?= $this->section('content'); ?>
<?php if (session()->getFlashdata('success')) : ?><div class="alert alert-success rounded-4"><?= esc(session()->getFlashdata('success')); ?></div><?php endif; ?>
<?php if (session()->getFlashdata('error')) : ?><div class="alert alert-danger rounded-4"><?= esc(session()->getFlashdata('error')); ?></div><?php endif; ?>
<form action="<?= base_url('/admin/faqs/bulk-delete'); ?>" method="post" data-bulk-scope data-bulk-form><?= csrf_field(); ?>
<div class="admin-card"><div class="admin-card-header"><div><span class="lead-card-kicker">Knowledge Base</span><h2>Daftar FAQ</h2></div><span class="lead-live-badge"><span></span> <?= count($faqs); ?> FAQ</span></div>
<div class="bulk-action-bar" data-bulk-toolbar hidden><div class="bulk-action-copy"><i class="bi bi-check2-square"></i><span><strong data-bulk-count>0</strong> FAQ dipilih</span></div><button class="btn btn-danger btn-sm rounded-pill" data-confirm="Pindahkan {count} FAQ ke Sampah?"><i class="bi bi-trash3"></i> Pindahkan ke Sampah</button></div>
<div class="table-responsive"><table class="admin-table"><thead><tr><th class="admin-select-cell"><input type="checkbox" class="admin-bulk-check" data-check-all></th><th>Pertanyaan</th><th>Jawaban</th><th>Urutan</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php if (empty($faqs)) : ?><tr><td colspan="6"><div class="admin-empty"><i class="bi bi-question-circle"></i> Belum ada data FAQ.</div></td></tr><?php else : ?><?php foreach ($faqs as $faq) : ?><tr><td class="admin-select-cell"><input type="checkbox" name="selected_ids[]" value="<?= esc($faq['id']); ?>" class="admin-bulk-check" data-bulk-item></td><td><strong><?= esc($faq['question'] ?? '-'); ?></strong></td><td><?= esc(mb_strimwidth($faq['answer'] ?? '-',0,110,'...')); ?></td><td><?= esc($faq['sort_order'] ?? 0); ?></td><td><span class="status-pill <?= ($faq['status'] ?? '') === 'active' ? 'status-success' : 'status-muted'; ?>"><?= ($faq['status'] ?? '') === 'active' ? 'Aktif' : 'Nonaktif'; ?></span></td><td><a href="<?= base_url('/admin/faqs/edit/' . $faq['id']); ?>" class="btn btn-admin-primary btn-sm">Edit</a></td></tr><?php endforeach; ?><?php endif; ?></tbody></table></div></div></form>
<?= $this->endSection(); ?>
