<?= $this->extend('templates/admin/layouts/main'); ?>
<?= $this->section('content_header'); ?>
<div class="admin-page-title d-flex flex-column flex-lg-row align-items-lg-end justify-content-between gap-3"><div><span>Konten Website</span><h1>Testimoni</h1><p>Kelola cerita dan pengalaman jamaah yang tampil di website.</p></div><div class="d-flex gap-2 flex-wrap"><a href="<?= base_url('/admin/testimonials/trash'); ?>" class="btn btn-admin-outline"><i class="bi bi-trash3"></i> Sampah</a><a href="<?= base_url('/admin/testimonials/create'); ?>" class="btn btn-admin-primary"><i class="bi bi-plus-lg"></i> Tambah Testimoni</a></div></div>
<?= $this->endSection(); ?>
<?= $this->section('content'); ?>
<?php if (session()->getFlashdata('success')) : ?><div class="alert alert-success rounded-4"><?= esc(session()->getFlashdata('success')); ?></div><?php endif; ?>
<?php if (session()->getFlashdata('error')) : ?><div class="alert alert-danger rounded-4"><?= esc(session()->getFlashdata('error')); ?></div><?php endif; ?>
<form action="<?= base_url('/admin/testimonials/bulk-delete'); ?>" method="post" data-bulk-scope data-bulk-form><?= csrf_field(); ?>
<div class="admin-card"><div class="admin-card-header"><div><span class="lead-card-kicker">Social Proof</span><h2>Daftar Testimoni</h2></div><span class="lead-live-badge"><span></span> <?= count($testimonials); ?> testimoni</span></div>
<div class="bulk-action-bar" data-bulk-toolbar hidden><div class="bulk-action-copy"><i class="bi bi-check2-square"></i><span><strong data-bulk-count>0</strong> testimoni dipilih</span></div><button class="btn btn-danger btn-sm rounded-pill" data-confirm="Pindahkan {count} testimoni ke Sampah?"><i class="bi bi-trash3"></i> Pindahkan ke Sampah</button></div>
<div class="table-responsive"><table class="admin-table"><thead><tr><th class="admin-select-cell"><input type="checkbox" class="admin-bulk-check" data-check-all></th><th>Nama</th><th>Label</th><th>Pesan</th><th>Rating</th><th>Urutan</th><th>Status</th><th>Aksi</th></tr></thead><tbody>
<?php if (empty($testimonials)) : ?><tr><td colspan="8"><div class="admin-empty"><i class="bi bi-chat-quote"></i> Belum ada data testimoni.</div></td></tr><?php else : ?>
<?php foreach ($testimonials as $testimonial) : ?><tr><td class="admin-select-cell"><input type="checkbox" name="selected_ids[]" value="<?= esc($testimonial['id']); ?>" class="admin-bulk-check" data-bulk-item></td><td><strong><?= esc($testimonial['name'] ?? '-'); ?></strong><br><small><?= !empty($testimonial['created_at']) ? date('d M Y', strtotime($testimonial['created_at'])) : '-'; ?></small></td><td><?= esc($testimonial['label'] ?? '-'); ?></td><td><?= esc(mb_strimwidth($testimonial['message'] ?? '-', 0, 90, '...')); ?></td><td><?php $rating=(int)($testimonial['rating']??5); for($i=1;$i<=5;$i++): ?><i class="bi <?= $i <= $rating ? 'bi-star-fill text-warning' : 'bi-star text-muted'; ?>"></i><?php endfor; ?></td><td><?= esc($testimonial['sort_order'] ?? 0); ?></td><td><span class="status-pill <?= ($testimonial['status'] ?? '') === 'active' ? 'status-success' : 'status-muted'; ?>"><?= ($testimonial['status'] ?? '') === 'active' ? 'Aktif' : 'Nonaktif'; ?></span></td><td><a href="<?= base_url('/admin/testimonials/edit/' . $testimonial['id']); ?>" class="btn btn-admin-primary btn-sm">Edit</a></td></tr><?php endforeach; ?>
<?php endif; ?></tbody></table></div></div></form>
<?= $this->endSection(); ?>
