<?= $this->extend('templates/admin/layouts/main'); ?>
<?= $this->section('content_header'); ?>
<div class="admin-page-title d-flex flex-column flex-lg-row align-items-lg-end justify-content-between gap-3"><div><span>Recycle Bin</span><h1>Sampah Testimoni</h1><p>Pulihkan testimoni atau hapus permanen secara massal.</p></div><div class="d-flex gap-2 flex-wrap"><a href="<?= base_url('/admin/recycle-bin'); ?>" class="btn btn-admin-outline"><i class="bi bi-trash3"></i> Pusat Sampah</a><a href="<?= base_url('/admin/testimonials'); ?>" class="btn btn-admin-outline"><i class="bi bi-arrow-left"></i> Kembali</a></div></div>
<?= $this->endSection(); ?>
<?= $this->section('content'); ?>
<?php if (session()->getFlashdata('success')) : ?><div class="alert alert-success rounded-4"><?= esc(session()->getFlashdata('success')); ?></div><?php endif; ?>
<?php if (session()->getFlashdata('error')) : ?><div class="alert alert-danger rounded-4"><?= esc(session()->getFlashdata('error')); ?></div><?php endif; ?>
<div class="admin-card"><div class="admin-card-header"><div><span class="lead-card-kicker">Data Terhapus</span><h2>Daftar Sampah</h2></div><?php if (session()->get('admin_role') === 'super_admin' && !empty($items)) : ?><form action="<?= base_url('/admin/testimonials/trash/empty'); ?>" method="post" data-confirm="Hapus permanen seluruh testimoni di Sampah?"><?= csrf_field(); ?><button class="btn btn-danger btn-sm rounded-pill"><i class="bi bi-trash3-fill"></i> Hapus Semua Sampah</button></form><?php endif; ?></div>
<form action="<?= base_url('/admin/testimonials/trash/bulk-action'); ?>" method="post" data-bulk-scope data-bulk-form><?= csrf_field(); ?><div class="bulk-action-bar" data-bulk-toolbar hidden><div class="bulk-action-copy"><i class="bi bi-check2-square"></i><span><strong data-bulk-count>0</strong> testimoni dipilih</span></div><div class="bulk-action-controls"><select name="bulk_action" class="form-select form-select-sm"><option value="restore">Pulihkan</option><?php if (session()->get('admin_role') === 'super_admin') : ?><option value="force_delete">Hapus permanen</option><?php endif; ?></select><button class="btn btn-admin-primary btn-sm" data-confirm="Jalankan aksi untuk {count} testimoni terpilih?">Terapkan</button></div></div><div class="table-responsive"><table class="admin-table"><thead><tr><th class="admin-select-cell"><input type="checkbox" class="admin-bulk-check" data-check-all></th><th>Nama</th><th>Label</th><th>Pesan</th><th>Dihapus</th></tr></thead><tbody><?php if (empty($items)) : ?><tr><td colspan="5"><div class="admin-empty"><i class="bi bi-trash3"></i> Sampah testimoni masih kosong.</div></td></tr><?php else : ?><?php foreach ($items as $item) : ?><tr><td class="admin-select-cell"><input type="checkbox" name="selected_ids[]" value="<?= esc($item['id']); ?>" class="admin-bulk-check" data-bulk-item></td><td><strong><?= esc($item['name']); ?></strong></td><td><?= esc($item['label'] ?? '-'); ?></td><td><?= esc(mb_strimwidth($item['message'] ?? '-',0,100,'...')); ?></td><td><?= !empty($item['deleted_at']) ? date('d M Y H:i', strtotime($item['deleted_at'])) : '-'; ?></td></tr><?php endforeach; ?><?php endif; ?></tbody></table></div></form></div>
<?= $this->endSection(); ?>
